function out1 = eqdHsp(q1,q2,q3,q4,q5)
%EQDHSP
%    OUT1 = EQDHSP(Q1,Q2,Q3,Q4,Q5)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    13-Mar-2019 21:26:49

t2 = q1+q2+q3+q4-q5;
t3 = sin(t2);
t4 = t3.*4.33782e-1;
t5 = q1+q2+q3+q4;
t6 = sin(t5);
t7 = t6.*4.2195e-1;
t8 = q1+q2;
t9 = sin(t8);
t10 = t4+t7;
out1 = [t4+t7-t9.*4.2195e-1-sin(q1).*4.33782e-1,t4+t7-t9.*4.2195e-1,t10,t10,-t4];
