function Lfyadq = eqLfyadq
%EQLFYADQ
%    LFYADQ = EQLFYADQ

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    13-Mar-2019 21:09:29

Lfyadq = reshape([-1.0,0.0,0.0,1.0,-1.0,1.0,0.0,1.0,-1.0,0.0,0.0,1.0,-1.0,0.0,0.0,0.0,5.069133794225295e-1,0.0,1.0,0.0],[4, 5]);
