function Lfya = eqLfya(dq1,dq2,dq3,dq4,dq5)
%EQLFYA
%    LFYA = EQLFYA(DQ1,DQ2,DQ3,DQ4,DQ5)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    13-Mar-2019 21:09:28

Lfya = [-dq1-dq2-dq3-dq4+dq5.*5.069133794225295e-1;dq2;dq5;dq1+dq2+dq3];
