function P = eqPspm(Ls,Lt,Wtr,q1,q2,q3,q4,q5)
%EQPSP
%    P = EQPSP(LS,LT,WTR,Q1,Q2,Q3,Q4,Q5)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    10-Nov-2018 15:58:34
n=length(q1);
t2 = sin(q1);
t3 = q1+q2;
t4 = sin(t3);
t6 = Lt.*t4;
t7 = Ls.*t2;
t5 = -t6-t7;
t8 = q1+q2+q3+q4;
t9 = sin(t8);
t10 = Lt.*t9;
t11 = cos(q1);
t12 = Ls.*t11;
t13 = cos(t3);
t14 = Lt.*t13;
t15 = t12+t14;
t16 = q1+q2+q3+q4-q5;
t17 = cos(t8);
P = reshape([-Ls.*t2,t12,zeros(n,1),t5,t15,zeros(n,1),t5,t15,Wtr*ones(n,1),-t6-t7+t10,t12+t14-Lt.*t17,Wtr*ones(n,1),-t6-t7+t10+Ls.*sin(t16),t12+t14-Lt.*t17-Ls.*cos(t16),Wtr*ones(n,1)]',[3, 5, n]);
P = permute(P,[1 3 2]);