function R = eqRsp(q1,q2,q3,q4,q5)
%EQRSP
%    R = EQRSP(Q1,Q2,Q3,Q4,Q5)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    13-Mar-2019 21:02:23

t2 = q1+q2;
t3 = q1+q2+q3;
t4 = q1+q2+q3+q4;
t5 = q1+q2+q3+q4-q5;
t6 = cos(q1);
t7 = cos(t2);
t8 = cos(t3);
t9 = cos(t4);
t10 = cos(t5);
t11 = sin(q1);
t12 = sin(t2);
t13 = sin(t3);
t14 = sin(t4);
t15 = sin(t5);
R = reshape([-t11,t6,0.0,-t6,-t11,0.0,0.0,0.0,1.0,-t12,t7,0.0,-t7,-t12,0.0,0.0,0.0,1.0,-t13,t8,0.0,-t8,-t13,0.0,0.0,0.0,1.0,-t14,t9,0.0,-t9,-t14,0.0,0.0,0.0,1.0,-t15,t10,0.0,t10,t15,0.0,0.0,0.0,-1.0],[3, 3, 5]);
