function ya = eqya(q1,q2,q3,q4,q5)
%EQYA
%    YA = EQYA(Q1,Q2,Q3,Q4,Q5)

%    This function was generated by the Symbolic Math Toolbox version 6.2.
%    13-Mar-2019 21:09:28

ya = [-q1-q2-q3-q4+q5.*5.069133794225295e-1;q2;q5;q1+q2+q3];
